[v1]
"broot 0.10.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["broot"]
"chars 0.4.1 (path+file:///Users/djm/Documents/Code/Github/chars/chars)" = ["chars"]
"cicada 0.9.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["cicada"]
"eva 0.2.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["eva"]
"pier 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["pier"]
"procs 0.8.16 (registry+https://github.com/rust-lang/crates.io-index)" = ["procs"]
"rargs 0.2.2 (git+https://github.com/lotabout/rargs.git#8ba96e710306f7788cf90198548665c6cd0f098b)" = ["rargs"]
"rga 0.5.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["rga", "rga-preproc"]
"skim 0.6.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["sk"]
"uutils 0.0.1 (path+file:///Users/djm/Documents/Code/Github/coreutils)" = ["uutils"]
"vivid 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["vivid"]
"xcp 0.7.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["xcp"]
