# https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
# Test on Both GNU/Linux and Mac OS
matrix:
  include:
    - name: Test on Mac OS X
      os: osx
      osx_image: xcode11.3
      sudo: required
      script:
        - set -eo pipefail
        - ./install < test/bootstrap-tools.txt
notifications:
  email: false
  irc: false
