name: CI

on: [push]

jobs:
  build:
    runs-on: [macos-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Bootstrap Tools
        run: |
          rm /usr/local/bin/node@12
          bash ./install < test/bootstrap-tools.txt
