name: CI

on: [push]

jobs:
  build:
    runs-on: [macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: echo -e "2\n4" > tmpfile
        run: ./install < tmpfile
